## INFORMATION
##  - Author: Pyeh
##  - Version: 0.0.1
##  - Created for: Nexus Role-Play
##
##
## PERMISSION
## admin - dni.permission.admin
## staff - dni.permission.show-other

MAIN: Pyeh